controller_list:
  - name: fake_iiwa_surgery_controller
    joints:
      - virtual_joint
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
initial:  # Define initial robot poses.
#  - group: iiwa_surgery
#    pose: home
